### ISSUE TITLE
[Bug] Dates are malformed using CDC mirror from PostgreSQL (12.14) to Snowflake

### ISSUE THREAD

**Issue by DanielTatarkin** [PeerDB-io/peerdb#1127]
PostgreSQL table DDL:

```sql
CREATE TABLE my_table(id varchar primary key, mydate date);

INSERT INTO public.my_table (id, mydate) VALUES ('1'::varchar, '1970-06-02'::date);
INSERT INTO public.my_table (id, mydate) VALUES ('2'::varchar, '1970-07-07'::date);
INSERT INTO public.my_table (id, mydate) VALUES ('3'::varchar, '1970-07-05'::date);
INSERT INTO public.my_table (id, mydate) VALUES ('4'::varchar, '1970-03-10'::date);
INSERT INTO public.my_table (id, mydate) VALUES ('5'::varchar, '1970-01-10'::date);
INSERT INTO public.my_table (id, mydate) VALUES ('6'::varchar, '1970-01-11'::date);
```

Gets replicated as the following to Snowflake via CDC initial copy mirror:

| ID (Varchar) | MYDATE (Date) |
|--------|--------|
| 1 | 2386-03-01 |
| 2 | 2481-12-27 |
| 3 | 2476-07-06 |
| 4 | 2156-03-06 |
| 5 | 1994-08-23 | 
| 6 | 1997-05-19 | 

**Issue:** The original dates from source table did not get carried over correctly to the destination
**Git Hash** used for testing: 6997d5e8daceb18173678cc4e6a843d408092002

**Comment by saisrirampur** [comment]
@iskakaushik @Amogh-Bharadwaj @serprex let us try to fix this at the soonest as it is a data related issue. Thanks for reporting this @DanielTatarkin !
