### ISSUE TITLE
unable to start PeerFlow workflow: Namespace default has no mapping defined for search attribute MirrorName

### ISSUE THREAD

**Issue by salilsaifuddin** [PeerDB-io/peerdb#1274]
while trying to mirror source to destination i am getting error "unable to start PeerFlow workflow: Namespace default has no mapping defined for search attribute MirrorName" how to resolve this issue
followed steps mentioned in "https://github.com/PeerDB-io/peerdb"

**Comment by serprex** [comment]
https://github.com/PeerDB-io/peerdb/blob/main/scripts/mirror-name-search.sh
