### ISSUE TITLE
Run UUID not listed on screen

### ISSUE THREAD

**Issue by goranc** [PeerDB-io/peerdb#1602]
In peerdb version 0.12.1 UI
On the Mirrors screen -> Initial load -> Progress table display
there is no Run UUID field displayed and other values are misplaced under labels

LIke in this example:
```
Partition UUID	Run UUID	Duration	Start Time	End Time	Rows In Partition	Rows Synced
89137197-8913-44f2-a8ba-6bb648646e18	16 minutes	2024-04-11 13:56:47	2024-04-11 14:12:38	999818	999818
```

**Comment by Amogh-Bharadwaj** [comment]
Thanks for raising this! This has been fixed here: https://github.com/PeerDB-io/peerdb/pull/1603

**Comment by Amogh-Bharadwaj** [comment]
We will soon be releasing v0.12.2 with this fix
