### ISSUE TITLE
Table list not cleared when mirror is deleted

### ISSUE THREAD

**Issue by goranc** [PeerDB-io/peerdb#1609]
When we create a mirror, execute and delete it after we finish.
Then we create a new mirror with the same name to repeat processing,
the list of tables in the initial load screen displays new tables and a list of tables from the previous run.

This behavior is intentional or is it not cascade deleted as it should be?

**Comment by iskakaushik** [comment]
not intentional @goranc , thanks for filing this issue, we will get to it. cc: @serprex

**Comment by serprex** [comment]
@iskakaushik this is somewhat intentional, what should the expected behavior be? Is this only about replacing initial load entries?

**Comment by iskakaushik** [comment]
@serprex my thought here is that when a flow gets deleted / dropped we should be clearing all the metadata associated with it, for example all the tables in peerdb_stats schema that reference this `flow_name` and also the errors associated with this flow that are stored in `flow_errors` table.

**Comment by serprex** [comment]
Then we need to come up with another way to recreate mirror while persisting history

**Comment by iskakaushik** [comment]
fair point, maybe we can have an optional flag in the delete request -- persist history, default it to false

**Comment by goranc** [comment]
Maybe it can be just marked as deleted, to not show history records for new runs with the same name,
but with a flag/switch to show history, to see what was run under the same name (intentional history view).

**Comment by Amogh-Bharadwaj** [comment]
This has been fixed by #2029 where an option (checkbox) is provided when deleting peers where you can choose to keep stats or not. Default - stats are deleted when you drop the mirror
