### ISSUE TITLE
[Clickhouse] Mirror a nullable row results in not nullable

### ISSUE THREAD

**Issue by erwannbst** [PeerDB-io/peerdb#1715]
Mirroring a nullable timestamp with time zone results in not nullable DateTime64(6)

It should result in Nullable(DateTime64(6))

Postgres source
<img width="533" alt="Screenshot 2024-05-14 at 13 55 17" src="https://github.com/PeerDB-io/peerdb/assets/16354899/6e7ff6ea-65bd-48ea-a5b2-a40020837c12">

Clickhouse mirror
<img width="553" alt="Screenshot 2024-05-14 at 13 55 02" src="https://github.com/PeerDB-io/peerdb/assets/16354899/d239ec63-1f74-49d1-bddf-13769a23391c">

**Comment by Amogh-Bharadwaj** [comment]
Hi @erwannbst !
This is intentional, as Clickhouse warns against using `Nullable` columns, as it affects performance etc.
https://clickhouse.com/docs/en/optimize/avoid-nullable-columns
