### ISSUE TITLE
Minio errors when following quickstart for clickhouse

### ISSUE THREAD

**Issue by zachblume** [PeerDB-io/peerdb#1727]
- Followed https://docs.peerdb.io/quickstart/quickstart
 - Installed on Ubuntu on hetzner with a local network and firewall rules allowing local network open port on 9000 for clickhouse
 - Added valid remote postgres peer, worked
 - Created clickhouse peer via web interface -- got errors. Tried via sql via the SQL get started guide -- same errors

```
root@peerdb:~/peerdb# psql "port=9900 host=localhost password=peerdb"
psql (16.2 (Ubuntu 16.2-1ubuntu4), server 14)
Type "help" for help.

root=> CREATE PEER local_clickhouse FROM CLICKHOUSE
WITH
(
    host='10.0.0.2',
    port=9000,
    user='default',
    password='...',
    database='default',
    disable_tls = true
);
ERROR:  User provided error: ErrorInfo {
  severity: "ERROR",
  code: "internal_error",
  message: '[peer]: invalid configuration: failed to validate peer local_clickhouse:
failed to validate S3 bucket: failed to write to bucket: operation error S3: PutObject,
exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: ,
HostID: , request send failed, Put "http://host.docker.internal:9001/peerdbbucket/peerdb_check9550a006-9868-451c-ae8a-ab63c31e0b0d?x-id=PutObject": dial tcp 127.0.0.1:9001: connect: connection refused',
  detail: None,
  hint: None,
  position: None,
  internal_position: None,
  internal_query: None,
  where_context: None,
  file_name: None,
  line: None,
  routine: None,
}
root=> 
```

Note: I had a different error before, referring to host.docker.internal as well. I added a /etc/hosts for host.docker.internal to 127.0.0.1 on the machine as well and now got the above error.

**Comment by mithleshjs** [comment]
Replace `host.docker.internal` with Public or Private IP of the server in http://host.docker.internal:9001

**Comment by thejoven** [comment]
same！

**Comment by balheru** [comment]
```bash
x-minio-config: &minio-config
  PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_ACCESS_KEY_ID: _peerdb_minioadmin
  PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_SECRET_ACCESS_KEY: _peerdb_minioadmin
  PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_REGION: us-east-1
  PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_ENDPOINT_URL_S3: http://minio:9000
  PEERDB_CLICKHOUSE_AWS_S3_BUCKET_NAME: peerdbbucket
  ```
  
Try this in the docker-compose.yml file

**Comment by serprex** [comment]
#1956

**Comment by ivanovmax** [comment]
> ```shell
> x-minio-config: &minio-config
>   PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_ACCESS_KEY_ID: _peerdb_minioadmin
>   PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_SECRET_ACCESS_KEY: _peerdb_minioadmin
>   PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_REGION: us-east-1
>   PEERDB_CLICKHOUSE_AWS_CREDENTIALS_AWS_ENDPOINT_URL_S3: http://minio:9000
>   PEERDB_CLICKHOUSE_AWS_S3_BUCKET_NAME: peerdbbucket
> ```
> 
> Try this in the docker-compose.yml file

I agree. Why docker-compose.yml in repo use host.docker.internal instead of direct minio address inside docker network?
