### ISSUE TITLE
source vs target extension

### ISSUE THREAD

**Issue by arist0v** [PeerDB-io/peerdb#1971]
I have an issue,

i have a target database that have the postgis extension,

the source database doesn'T have the extension

so it could be nice to have a way to sync data from a source to a target (i wanted to use sql query directly on source) and between the select and insert been able to add extension function that the source didn'T have.

would be a nice ETL feature you didn't provide

**Comment by serprex** [comment]
this has some challenges to do correctly, so unfortunately isn't going to fit on our roadmap
