### ISSUE TITLE
Unable to edit postgres peer when connectivity is lost

### ISSUE THREAD

**Issue by iskakaushik** [PeerDB-io/peerdb#2018]
Steps to reproduce:

1. create a postgres peer
2. change the password of postgres db
3. try to edit the peer via regular flow, it doesn't work as in postgres page we try to render stuff by connecting to postgres instance.

Fix:

1. Expose an edit link for the `/peers` page that bypasses this.
2. Better error reporting if unable to connect to postgres peer.

**Comment by iskakaushik** [comment]
will be fixed by https://github.com/PeerDB-io/peerdb/pull/1998

**Comment by Amogh-Bharadwaj** [comment]
fixed by https://github.com/PeerDB-io/peerdb/pull/1998
