### ISSUE TITLE
Add support for S3 peer for Query Replication

### ISSUE THREAD

**Issue by iskakaushik** [PeerDB-io/peerdb#202]
## Context:

When we replicate a query to snowflake, we already stage to an S3 bucket. We write avro files to that S3 bucket and then we issue a COPY command to copy from the external S3 stage to the snowflake table. We can think of this as a transitional stage.

### code references: 

* `aws.go` (credentials)
* `snowflake/qrep_avro_sync.go`
* `snowflake/qrep.go` is the entry point for query replication.

## Requirement:

Treat S3 as a first class Peer so that we can write Avro to the S3 destination as a final point.

## Approach:

1. In `peers.proto` add definition for an S3 peer. This would be the following
    a. S3 url: `s3://<bucket_name>/<prefix>`
2. create a connector for `S3`, the same way we do it for Snowflake, BQ, etc. All the CDC methods will error saying not supported, only query replication will be supported.
3. When we get a batch of records from the source, we will write them as avro files to the given s3 url. Most of this logic already exists in `snowflake/qrep_avro_sync.go`, refactor to reuse.
4. Make it so that down the line its easy to support `parquet` etc.

**Comment by wwzeng1** [comment]
Hi @iskakaushik!
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try.
We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)
