### ISSUE TITLE
Quick start fails due to invalid temporal admin tools tag

### ISSUE THREAD

**Issue by dagleaves** [PeerDB-io/peerdb#2070]
https://github.com/temporalio/docker-builds/issues/222

The 1.24 tag for temporal admin tools does not work in the quick start guide's docker-compose file. The latest is temporalio/admin-tools:1.24.2-tctl-1.18.1-cli-1.0.0 -- there is no 1.24 tag.

**Comment by heavycrystal** [comment]
This should be fixed, we're using a valid tag now
