### ISSUE TITLE
Namespace default has no mapping defined for search attribute

### ISSUE THREAD

**Issue by ujae7142** [PeerDB-io/peerdb#2098]
hi there,

always get this error when create mirror from postgres to clickhouse

flow_api              | {"time":"2024-09-25T07:46:06.150051158Z","level":"ERROR","msg":"unable to start PeerFlow workflow","error":"Namespace default has no mapping defined for search attribute MirrorName","deploymentUid":""}

**Comment by ujae7142** [comment]
i'm new to peerdb,

following https://docs.peerdb.io/quickstart/quickstart#quickstart
get the same error

**Comment by iamKunalGupta** [comment]
Hi @ujae7142 were you able to solve this issue? You need to create a `MirrorName` search attribute on the temporal namespace, which should actually happen via https://github.com/PeerDB-io/peerdb/blob/main/docker-compose.yml#L98

**Comment by iamKunalGupta** [comment]
Closing for now due to lack of information
