### ISSUE TITLE
Timestamp Microseconds Discrepancy During CDC Sync from PostgreSQL to ClickHouse Using PeerDB

### ISSUE THREAD

**Issue by sandom123** [PeerDB-io/peerdb#2160]
This might be a bug:

When using PeerDB to perform real-time CDC synchronization from PostgreSQL to ClickHouse, there is a discrepancy in the timestamp format. eg: The original timestamp 2024-10-17 11:13:43.117115 from PostgreSQL is being changed to 2024-10-17 11:13:43.117000 in ClickHouse, where the microseconds are being rounded or truncated.

**Comment by sandom123** [comment]
@iamKunalGupta  @Amogh-Bharadwaj This problem does not occur in Initial Copy and is not easy to detect, but it does exist.  Hi bro, pls help me.

**Comment by Amogh-Bharadwaj** [comment]
Hi @sandom123 ! 
Thanks for flagging

It might be that we are coercing to a lower precision. We are currently prioritising testing of the product and will mark this as one of the items. You can expect this to get fixed by mid-next week !

**Comment by sandom123** [comment]
Okk, thank you bro. @Amogh-Bharadwaj

**Comment by heavycrystal** [comment]
should be closed by #2181, please test and reopen the issue if this doesn't fix your problem
thanks for reporting!
