### ISSUE TITLE
s3 upload partSize too small?

### ISSUE THREAD

**Issue by joltcan** [PeerDB-io/peerdb#2184]
Initial load problem with partSize, is it possible to raise it with a configuration somewhere?

```
psql (initial loafailed to sync records: failed to write records to S3: failed to upload file to path 
s3://peerdb-cache/...... 4890f21240e1.avro.zst: 
upload multipart failed, upload id: OTA0ZTE5NTMtMTdiMi00MWE5LWJhY....., 
cause: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit
```

**Comment by serprex** [comment]
which connector are you using?

https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html may be something we can adjust with our use of s3 sdk

**Comment by joltcan** [comment]
Dang it! Of course I forgot to say the details: I'm running latest docker compose with psql 12 as source and clickhouse as destination.

I did configure another s3 bucket as well (minio, on prem), I see all tables up until the one that breaks (huge (for us), almost 5 billion rows) on our minio, but it looks like it broke on the minio cache locally?

**Comment by serprex** [comment]
I think so

**Comment by joltcan** [comment]
Is it possible to skip the s3 part and just store it locally on disk?

**Comment by serprex** [comment]
Not quite, most data warehouses have specialized support for ingesting from s3

**Comment by joltcan** [comment]
Seems like it would be possible to add the multipart size and change that, but I have very little experience with go, so maybe this isn't even the right solution. Gonna try and modify `flow/connectors/utils/avro/avro_writer.go` and see how it goes

```
_, err = manager.NewUploader(s3svc, func(u *s3manager.Uploader) {
    u.PartSize = 500 * 1024 * 1024 // Set part size to 500 MB
}).Upload(ctx, &s3.PutObjectInput{
    Bucket: aws.String(bucketName),
    Key:    aws.String(key),
    Body:   r,
})
```

If the multipart limit is 10k and default part size is 5 MB, then I assume my parts just needs to be bigger for it to work.

Psql says the table is 2 TB btw, so 470k parts in 5 MB would be needed

**Comment by serprex** [comment]
Please let us know how that goes, I can add an env variable to configure it if it works

re size, note data gets encoded into avro, so may be larger than tables in postgres

**Comment by joltcan** [comment]
Ill give it a shot and get back to you. The peerdb product itself is amazing and I really want to succeed with this. Cheers.
