### ISSUE TITLE
Cannot parse type Decimal(76, 38)

### ISSUE THREAD

**Issue by chaishiqi** [PeerDB-io/peerdb#2295]
When syncing from postgresql to clickhouse with XMIN, some error occurs, details as below:

```
failed to sync records: code: 376, message: Cannot parse type Decimal(76, 38), expected non-empty binary data with size equal to or less than 32, got 48: (at row 1792)\n:  While executing AvroRowInputFormat: While executing S3Source
```
source pg column type is numeric(128)
dest clickhouse column type is Decimal(76, 38)

how to resolve it?

**Comment by iamKunalGupta** [comment]
@chaishiqi what PeerDB version are you running?

**Comment by iamKunalGupta** [comment]
Atlantis the minimum the version would be set to v0.19.x

**Comment by chaishiqi** [comment]
> I believe you are running ./run-peerdb.sh after cloning the repository. There was recently an issue where the latest-stable was pointing to the version you specified. Can you do a `git pull` and re run peerdb? This versioning was fixed recently.

All have been ok after I update the image tag of docker-compose.yaml to latest-dev,  thx
