### ISSUE TITLE
ARRAY<UUID> not handled properly

### ISSUE THREAD

**Issue by lukejudd-lux** [PeerDB-io/peerdb#2315]
[array.rs](https://github.com/PeerDB-io/peerdb/blob/main/nexus/value/src/array.rs) doesn't handle arrays of UUIDs

the [lib.rs](https://github.com/PeerDB-io/peerdb/blob/main/nexus/value/src/lib.rs) does handle UUIDs

Can we please extend array processing to include `ARRAY<UUID>`

**Comment by serprex** [comment]
@lukejudd-lux does #2316 address your ask?
