### ISSUE TITLE
Runtime error: nil pointer dereference in StartNormalize activity on PostgresConnector

### ISSUE THREAD

**Issue by seonghobae** [PeerDB-io/peerdb#2354]
**Description:**  
When running the `StartNormalize` activity in the PeerDB project (using the `PostgresConnector`), we encountered a runtime error due to a nil pointer dereference. This issue occurred repeatedly during normalization steps and appears to originate from `normalize_stmt_generator.go` and `postgres.go` within the Postgres connector logic.

**Steps to Reproduce:**  
1. Run a workflow that triggers the `StartNormalize` activity in a Temporal setup.  
2. Observe the workflow execution logs during the normalization phase.  
3. The error `runtime error: invalid memory address or nil pointer dereference` appears consistently, halting the normalization process.

**Expected Behavior:**  
The `StartNormalize` activity should execute successfully, generating all necessary normalization statements and completing without runtime panics.

**Actual Behavior:**  
The workflow fails at the `StartNormalize` activity with a panic caused by a nil pointer dereference. The provided stack trace shows that `generateFallbackStatements` in `normalize_stmt_generator.go:80` attempts to access an uninitialized object.

**Relevant Logs (Redacted for Security):**  
```
{"time":"2024-12-13T08:04:03Z","level":"ERROR","msg":"Activity panic.","ActivityType":"StartNormalize","PanicError":"runtime error: invalid memory address or nil pointer dereference","PanicStack":".../normalize_stmt_generator.go:80 +0x3d ..."}
```

**Additional Context:**  
- Ensuring that all structs and pointers are properly initialized before usage may prevent this error.  
- Adding defensive checks for `nil` before dereferencing objects in `generateNormalizeStatements` or `generateFallbackStatements` could be a potential fix.  
- It might be helpful to add logging or assertions around these code paths to identify uninitialized states earlier.

**Comment by serprex** [comment]
Looks like same thing as https://github.com/PeerDB-io/peerdb/pull/2317 will need to replicate fix beyond snowflake

**Comment by heavycrystal** [comment]
should be fixed by https://github.com/PeerDB-io/peerdb/pull/2357
