### ISSUE TITLE
Cannot connect using psql

### ISSUE THREAD

**Issue by frafra** [PeerDB-io/peerdb#253]
Hi,
I just followed the [quickstart](https://docs.peerdb.io/quickstart), but psql cannot connect.

```bash
$ psql --version
psql (PostgreSQL) 13.11 (Ubuntu 13.11-1.pgdg22.04+1)
$ psql "port=9900 host=localhost password=peerdb"
psql: error: connection to server at "localhost" (::1), port 9900 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Revision 5a99d46066071a8faa8247dfd7433990f3d8e934. Docker rootless on Ubuntu 22.04. All containers up and running, no error shown in the logs.

**Comment by saisrirampur** [comment]
Interesting. This shouldn't be happening. Can you check if 9900 is open ` sudo lsof -i:9900`? Also check docker logs - window where you started docker. It is possible that the peerdb-server might not have started.

**Comment by frafra** [comment]
> Interesting. This shouldn't be happening. Can you check if 9900 is open ` sudo lsof -i:9900`? Also check docker logs - window where you started docker. It is possible that the peerdb-server might not have started.

No, I am sorry, I am not root on that machine. peerdb-server is up and running, and should be listening on 0.0.0.0:9900. Could it be that it is blocking some IP ranges or only accepting connections from localhost?

**Comment by iamKunalGupta** [comment]
@frafra can you try connecting via this:
`docker exec -it peerdb-server psql "port=9900 host=localhost password=peerdb user=postgres"`

**Comment by serprex** [comment]
Given #510 can no longer be reproduced, going to assume this falls under that. Please open a new ticket if you'd like me to investigate further
