### ISSUE TITLE
Clickhouse sink support

### ISSUE THREAD

**Issue by zifeo** [PeerDB-io/peerdb#254]

**Comment by saisrirampur** [comment]
Thanks for reporting this. Will take this into account into our product prioritization. Also feel free to checkout our code and submit a PR, if you get time! :)

**Comment by detygon** [comment]
It's definitely needed, It was the first thing I looked for.

**Comment by maxtushewski** [comment]
me too

**Comment by saisrirampur** [comment]
@maxtushewski @detygon @zifeo and others we just added support for Clickhouse connector - #969. Let us know if you'd be interested to testing it out. I'd love a quick chat to assist with testing and get feedback! :)

**Comment by detygon** [comment]
I'm very interested in testing this new feature. @saisrirampur

**Comment by saisrirampur** [comment]
Ack @detygon. ClickHouse connector is in beta and is ready to be stress tested. Happy to assist with the testing. Do you have sometime this or next week for a quick catchup? I am sharing my [calendar](https://calendly.com/sai-peerdb/30min) to make scheduling easier. Looking forward to connecting!

**Comment by iskakaushik** [comment]
https://blog.peerdb.io/postgres-to-clickhouse-real-time-replication-using-peerdb it's now in!
