### ISSUE TITLE
User needs to be aware of BigQuery rows per request limit

### ISSUE THREAD

**Issue by Amogh-Bharadwaj** [PeerDB-io/peerdb#321]
We are hardcoding the FETCH limit of the cursor for each worker's PullRecordStream to 262144. BigQuery has a row size limit of, I believe, 50,000 rows per request. 
Our merge statement for multi-insert in BigQuery is an insert-into-select statement and so if, say, you have a table to sync which has 204,000 rows and you've set the `num_rows_per_partition` to 51,000, then each worker will try to push 51,000 rows with a single insert-into-select command which is not something BigQuery can handle.

**Comment by iskakaushik** [comment]
Seems like this is when not using `avro`, @Amogh-Bharadwaj , can you please try `snapshot_sync_mode = 'avro'` and update this bug?
