### ISSUE TITLE
Unable to create peer 

### ISSUE THREAD

**Issue by prashant-junio** [PeerDB-io/peerdb#418]
Postgres Version: psql (PostgreSQL) 15.4 (Homebrew)
<img width="929" alt="Screenshot 2023-09-25 at 10 07 30 AM" src="https://github.com/PeerDB-io/peerdb/assets/126768751/58723346-3f55-4ff9-b885-b84b5243b22b">

I've followed every step in docs, and found i'm unable to create peer.
Those cred in image is correct and it tested with tableplus.

**Comment by p-bucky** [comment]
issue #419
