### ISSUE TITLE
 Unable to create peer

### ISSUE THREAD

**Issue by p-bucky** [PeerDB-io/peerdb#419]
Postgres Version: psql (PostgreSQL) 15.4 (Homebrew)
<img width="929" alt="Screenshot 2023-09-25 at 10 07 30 AM" src="https://github.com/PeerDB-io/peerdb/assets/59308744/6825a51d-9c27-4cda-9480-2a25a68fd779">
I've followed every step in docs, and found i'm unable to create peer.
Those cred in image is correct and it tested with tableplus.

**Comment by prashant-junio** [comment]
Using `host.docker.internal` worked
`CREATE PEER target FROM POSTGRES WITH
(
    host = 'host.docker.internal',
    port = '5455',
    user = 'admin',
    password = 'admin',
    database = 'target'
);`

**Comment by p-bucky** [comment]
Using `host.docker.internal` worked
`CREATE PEER target FROM POSTGRES WITH (
 host = 'host.docker.internal', port = '5455', 
 user = 'admin', 
 password = 'admin', 
 database = 'target' 
 );`
