### ISSUE TITLE
Mirrored Table schema changes

### ISSUE THREAD

**Issue by iskakaushik** [PeerDB-io/peerdb#421]
DDL | Propagation
-- | --
ALTER TABLE ADD COLUMN |  Replay the added column on the target side
ALTER TABLE ADD COLUMN DEFAULT | Partially reflected is okay. In the destination, rows synced prior to the ADD COLUMN operation have null values in the newly-added column. Re-sync the table if you want to update the existing rows in the destination with the default value.
Don't allow ALTER TABLE DROP COLUMN | Can lead to chaining issues.

**Comment by heavycrystal** [comment]
Closed by #368, #480 and #503
