### ISSUE TITLE
Support PostGIS and Enum data types

### ISSUE THREAD

**Issue by iskakaushik** [PeerDB-io/peerdb#427]
### PG -> PG

* If enum exists and cardinality matches - use the enum type
* Else store as VARCHAR

### PG -> SF/BQ

* Store as VARCHAR 

## Geospatial

* PG -> PG the datatypes should be matched perfectly.
* PG -> SF - https://docs.snowflake.com/en/sql-reference/data-types-geospatial#label-data-types-geography where possible and VARCHAR otherwise.
* PG -> BQ - https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#geography_type where possible and VARCHAR otherwise

**Comment by iskakaushik** [comment]
also support `HSTORE`

**Comment by serprex** [comment]
Issues: #563 #564 #565 #566
