### ISSUE TITLE
Tag latest dev image with `latest` and latest stable image with `stable` tag

### ISSUE THREAD

**Issue by iskakaushik** [PeerDB-io/peerdb#478]
Also the following maintenance items:

- [ ] Rename the docker files to more standard ones, `nexus` to `peerdb-server` and `ui` to `peerdb-ui`
- [ ] In the compose file also call the components with `peerdb-server` instead of underscores `peerdb_server`
- [ ] Publish the `peerdb-ui` docker image as part of the release actions

**Comment by heavycrystal** [comment]
Closed by #485
