### ISSUE TITLE
Bug: Unable to connect with psql 16.0

### ISSUE THREAD

**Issue by iamKunalGupta** [PeerDB-io/peerdb#510]
psql version:
```shell
❯  psql --version
psql (PostgreSQL) 16.0
```

Peerdb commit 4481888ec255518641d2bb42c415a560e3a10497

## Code
```
❯  psql "port=9900 host=localhost password=peerdb"
psql: error: connection to server at "bore.pub" (159.223.171.199), port 21331 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Trace logs from server:
[working.log](https://github.com/PeerDB-io/peerdb/files/12894453/working.log)
[non-working.log](https://github.com/PeerDB-io/peerdb/files/12894456/non-working.log)

The issue does not happen with psql from within the container (version 14.0) or version 15.0

Maybe need to advertise a higher version.

Maybe related to https://github.com/PeerDB-io/peerdb/issues/253

**Comment by serprex** [comment]
This is no longer an issue
