### ISSUE TITLE
Concurrent updates to peerdb_mirror_jobs table not allowed in BigQuery

### ISSUE THREAD

**Issue by saisrirampur** [PeerDB-io/peerdb#52]
https://cloud.google.com/bigquery/docs/transactions#transaction_concurrency

We plan to run SyncFlow and NormalizeFlow (for the same mirror) asynchronously. Both of these can issue conflicting (same row) UPDATE the peerdb_mirror_jobs table and BigQuery cancels one of the UPDATEs. This could happen often, once we make the workflow run async.

I checked if bigquery provides ability to explicitly acquire LOCKs and it [doesn't seem](https://stackoverflow.com/questions/51009354/is-it-possible-to-lock-some-table-records-in-bigquery) to. @iskakaushik any ideas on how we can address this issue? Does temporal provide a way of controlling the execution of 2 related but async workflows? Or any other design we can follow?

Snowflake might not have this issue as it does the required locking https://docs.snowflake.com/en/sql-reference/transactions#resource-locking (read UPDATE, DELETE, MERGE etc) cc @heavycrystal

**Comment by serprex** [comment]
This is no longer relevant now that metadata is stored in catalog, not destination
