### ISSUE TITLE
Make `zstd` the default for AVRO streaming where possible

### ISSUE THREAD

**Issue by iskakaushik** [PeerDB-io/peerdb#543]
Things that I'm aware of:

qrep:

- [x] pg -> sf via local staging (DONE)
- [ ] pg -> sf via S3
- [ ] pg -> bq (? is it possible)
- [ ] pg -> others optionally?

CDC:

think about it.

**Comment by heavycrystal** [comment]
From BigQuery docs:

```
BigQuery supports the following compression codecs for Avro file contents:

    Snappy
    DEFLATE
```

From Snowflake Docs:

```
COMPRESSION = AUTO | GZIP | BROTLI | ZSTD | DEFLATE | RAW_DEFLATE | NONE
```

**Comment by iskakaushik** [comment]
@heavycrystal  I'll let you pick one for BQ, whatever makes sense.

**Comment by iskakaushik** [comment]
@heavycrystal  can we close this?

**Comment by serprex** [comment]
BQ uses deflate
