### ISSUE TITLE
Server side encryption for S3 Peer

### ISSUE THREAD

**Issue by saisrirampur** [PeerDB-io/peerdb#819]
We [don't ](https://github.com/PeerDB-io/peerdb/blob/f33c34f884a104c78de2be70deea3bb56ee839d2/flow/connectors/s3/s3.go#L114C24-L114C33)seem to support server side encryption in its PutObject pushing while loading data to S3.

**Comment by Amogh-Bharadwaj** [comment]
[S3 automatically encrypts all objects uploaded to a bucket.](https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-encryption-faq.html)

**Comment by heavycrystal** [comment]
What is the requirement here? Do we want a level of encryption greater than the default?

**Comment by Amogh-Bharadwaj** [comment]
> [S3 automatically encrypts all objects uploaded to a bucket.](https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-encryption-faq.html)

Closing in view of the above comment
